### ISSUE TITLE
Time counter is slower when the tab is not active

### ISSUE THREAD

**Issue by marc2332** [start-again/pmdr#5]
## Bug Report

**Current Behavior**
The time counter goes slower when the tab is not active.

**Expected behavior/code**
The counter's speed should be the same always, no matter what.

**Environment**
- Browser name and version(s): Firefox v74
- OS: Windows 10

**Possible Solution**
Use this library -> https://github.com/turuslan/HackTimer This will maintain the counter's speed the same, even when the tab is not active.

**Comment by LucasCtrl** [comment]
Successfully patched with HackTimer!
Thank you!
